[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install", "npm install --prefix backend"]

[phases.build]
cmds = ["npm run build --prefix backend"]

[start]
cmd = "node backend/dist/server.js"
